spring:
  application:
    name: core
  datasource:
    url: jdbc:postgresql://localhost:5432/obs
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true

admin:
  username: ${OBS_ADMIN_USERNAME:admin}
  password: ${OBS_ADMIN_PASSWORD:admin}

crc:
  secret-key: ${CRC_SECRET_KEY:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}

jwt:
  secret-key: ${JWT_SECRET_KEY:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}
  expiration: ${JWT_EXPIRATION:3600000}

log:
   query-host: ${LOG_QUERY_HOST:localhost:3100}
trace:
   query-host: ${TRACE_QUERY_HOST:localhost:3200}
metric:
   query-host: ${METRIC_QUERY_HOST:localhost:9009}

server:
  error:
    include-stacktrace: never
